baseURL = "https://athul.github.io"
languageCode = "zh-cn"
title = "Yisheng's writings"
theme="archie"
copyright = "© Yisheng Gong"

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "short stories"

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gongyisheng"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/orange97648"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
